# Generated by Django 5.1.3 on 2024-12-05 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_remove_booking_user'),
        ('login', '0001_initial'),
        ('payments', '0002_remove_payment_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
