# Generated by Django 5.1.3 on 2024-12-06 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_booking_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
