# Generated by Django 5.1.3 on 2024-12-06 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='start_time',
        ),
    ]
