# Generated by Django 5.1.3 on 2024-12-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_remove_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymclass',
            name='Price',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=10),
        ),
    ]
